### ISSUE TITLE
Crashes with pretty much any input

### ISSUE THREAD

**Issue by swampservers** [mathiasbynens/luamin#81]
luamin -f test.lua
```
Cannot read property 'value' of undefined

Error: failed to minify. Make sure the Lua code is valid.
If you think this is a bug in luamin, please report it:
https://github.com/mathiasbynens/luamin/issues/new

Stack trace using luamin@1.0.4 and luaparse@0.2.1:

TypeError: Cannot read property 'value' of undefined
    at unexpected (/usr/local/lib/node_modules/luamin/node_modules/luaparse/luaparse.js:499:55)
    at lex (/usr/local/lib/node_modules/luamin/node_modules/luaparse/luaparse.js:627:12)
    at end (/usr/local/lib/node_modules/luamin/node_modules/luaparse/luaparse.js:2092:17)
    at parse (/usr/local/lib/node_modules/luamin/node_modules/luaparse/luaparse.js:2065:31)
    at minify (/usr/local/lib/node_modules/luamin/luamin.js:621:6)
    at /usr/local/lib/node_modules/luamin/bin/luamin:69:14
    at Array.forEach (<anonymous>)
    at main (/usr/local/lib/node_modules/luamin/bin/luamin:55:12)
    at /usr/local/lib/node_modules/luamin/bin/luamin:99:3
    at Object.<anonymous> (/usr/local/lib/node_modules/luamin/bin/luamin:113:2)
```

I get the same error in any file I try.

**Comment by swampservers** [comment]
It seems like the issue is caused by a byte order mark "EF BB BF", i think this is probably more appropriate to raise the issue in luaparse
